# Testing the use of R

```{r}
library(tidyverse)
library(cowplot)
library(ggradar)
library(ggstatsplot)
library(ggExtra)
library(corrplot)
```


```{r}
theme_set(
  theme_minimal_hgrid(10)
)
```


```{r}
df <- read_csv("../../data_collection/data/labelled/academic_data_3.csv")
df <- df %>%
  rename(
    D1 = `Data Gathering, Preparation and Exploration`,
    D2 = `Data Representation and Transformation`,
    D3 = `Computing with Data`,
    D4 = `Data Modeling`,
    D5 = `Data Visualization and Presentation`,
    D6 = `Science about Data Science`,
    D7 = `Not determinable`
  )
attach(df)
```
```{r}

fw_labels <- c(
  "D1",
  "D2",
  "D3",
  "D4",
  "D5",
  "D6")

fw_labels
```
```{r}

```


```{r, include=TRUE}
# testing script
source("viz_functions.R", local = knitr::knit_global())
count_by_country_type <- count_entries_by_country(df, type)
count_by_country_type
```


```{r}
df %>%
    filter(country == "India") %>%
    head()


```

``` {r}

program_radar(df, "Harvard University")

```

```{r}


ggbetweenstats(
  data = df,
  x = country, #type
  y = D1,
  title = "Distribution of division's proportions across countries",
  #outlier.tagging = TRUE,
  #outlier.label = uni_name
)

ggbetweenstats(
  data = df,
  x = country, #type
  y = D2,
  title = "Distribution of division's proportions across countries",
  #outlier.tagging = TRUE,
  #outlier.label = uni_name
)

ggbetweenstats(
  data = df,
  x = country, #type
  y = D3,
  title = "Distribution of division's proportions across countries",
  #outlier.tagging = TRUE,
  #outlier.label = uni_name
)

ggbetweenstats(
  data = df,
  x = country, #type
  y = D4,
  title = "Distribution of division's proportions across countries",
  #outlier.tagging = TRUE,
  #outlier.label = uni_name
)

ggbetweenstats(
  data = df,
  x = country, #type
  y = D5,
  title = "Distribution of division's proportions across countries",
  #outlier.tagging = TRUE,
  #outlier.label = uni_name
)

ggbetweenstats(
  data = df,
  x = country, #type
  y = D6,
  title = "Distribution of division's proportions across countries",
  #outlier.tagging = TRUE,
  #outlier.label = uni_name
)


```


```{r}

# ggdotplotstats has some error

grouped_ggscatterstats(
  data = df,
  x = D1,
  y = national_rank_qs,
  grouping.var = type,  # country
  marginal.type = 'boxplot',
  plotgrid.args = list(nrow = 1)
)

```


```{r}

ggcorrmat(
  data = df %>% select(fw_labels)
)

grouped_ggcorrmat(
  data = df %>% select(c(fw_labels, "country")),
  grouping.var = country
)

```